projects:
  InstagramClone:
    schemaPath: amplify/backend/api/InstagramClone/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: ap-southeast-1
        apiId: null
        maxDepth: 3
extensions:
  amplify:
    version: 3
